version: '2.1'
networks:
  default:
    external:
      name: spring-cloud-network
services:
  config-server:
    container_name: config-server
    build: ./config
    image: topbaby/config-service
    environment:
      - PROFILE_ACTIVE=production
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://config-user:topbaby@config-server:8080/health"]
        interval: 30s
        timeout: 10s
        retries: 5

  registry-server:
    container_name: registry-server
    build: ./registry
    image: topbaby/registry-service
    environment:
      - PROFILE_ACTIVE=production
      - CONFIG_SERVER=config-server
      - CONFIG_PORT=8080
      - CONFIG_USER=config-user
      - CONFIG_PWD=topbaby
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://registry-server:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8081:8081

  gateway-server:
    container_name: gateway-server
    build: ./gateway
    image: topbaby/gateway-service
    environment:
      - PROFILE_ACTIVE=production
      - REGISTRY_SERVER=registry-server
      - REGISTRY_PORT=8081
      - CONFIG_SERVER=config-server
      - CONFIG_PORT=8080
      - CONFIG_USER=config-user
      - CONFIG_PWD=topbaby
      - VIRTUAL_HOST=rest.61topbaby.com
      - LETSENCRYPT_HOST=rest.61topbaby.com
      - LETSENCRYPT_EMAIL=qing.wang@61topbaby.com
    restart: always
    depends_on:
      registry-server:
        condition: service_healthy
    ports:
      - 8082:8082

  auth-server:
    container_name: auth-server
    build: ./auth-service
    image: topbaby/auth-service
    environment:
      - PROFILE_ACTIVE=production
      - REGISTRY_SERVER=registry-server
      - REGISTRY_PORT=8081
      - DB_HOST=10.10.106.110
      - DB_PORT=3306
      - DB_NAME=topbaby_db
      - DB_USER=root
      - DB_PWD=61TopbabyHADB@2016
      - CONFIG_SERVER=config-server
      - CONFIG_PORT=8080
      - CONFIG_USER=config-user
      - CONFIG_PWD=topbaby
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    depends_on:
      registry-server:
        condition: service_healthy
    ports:
      - 8083:8083